name: Deploy to Simply.com FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: linux184.unoeuro.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /Portfolio/
          protocol: ftps

      - name: Replace SMTP credentials in PHP file
        run: |
          sed -i 's/DIN_EMAIL_BRUGERNAVN/${{ secrets.MAIL_SMTP_USERNAME }}/g' mail.php
          sed -i 's/DIN_EMAIL_ADGANGSKODE/${{ secrets.MAIL_SMTP_PASSWORD }}/g' mail.php